export const ACCOUNT_FETCH_LIST_SUCCESS = "ACCOUNT_FETCH_LIST_SUCCESS";
export const ACCOUNT_FETCH_LIST_FAIL = "ACCOUNT_FETCH_LIST_FAIL";
export const EDIT_ACCOUNT_COLOR_PICKER_VISIBLE="EDIT_ACCOUNT_COLOR_PICKER_VISIBLE"
export const EDIT_ACCOUNT_ITEM_SELECTED="EDIT_ACCOUNT_ITEM_SELECTED"


export const EDIT_ACCOUNT_INPUT_CHANGE="EDIT_ACCOUNT_INPUT_CHANGE";
export const GET_ACCOUNT_NAME_SUCCESS="GET_ACCOUNT_NAME_SUCCESS";
export const GET_ACCOUNT_NAME_FAIL="GET_ACCOUNT_NAME_FAIL";

export const UPDATE_ITEM_SUCCESS="UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAIL="UPDATE_ITEM_FAIL";

export const DELETE_ACCOUNT_SUCCESS="DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAIL="DELETE_ACCOUNT_FAIL";

export const ACCOUNT_DELETE_SUCCESS="ACCOUNT_DELETE_SUCCESS"

export const TRANSFER_ACCOUNT_FETCH_LIST_SUCCESS="TRANSFER_ACCOUNT_FETCH_LIST_SUCCESS"
export const TRANSFER_ACCOUNT_FETCH_LIST_FAIL="TRANSFER_ACCOUNT_FETCH_LIST_FAIL"
export const TRANSFER_VISIBLE_LIST="TRANSFER_VISIBLE_LIST"
export const TRANSFER_AMOUNT_CHANGE="TRANSFER_AMOUNT_CHANGE"
export const TRANSFER_AMOUNT_CHANGE_INVALID="TRANSFER_AMOUNT_CHANGE_INVALID";

export const TRANSFER_DATE_CHANGED="TRANSFER_DATE_CHANGED";
export const TRANSFER_NOTES_CHANGE="TRANSFER_NOTES_CHANGE";
export const TRANSFER_VISIBLE_LIST_2="TRANSFER_VISIBLE_LIST_2";

export const TRANSFER_IS_SELECTED_1="TRANSFER_IS_SELECTED_1";
export const TRANSFER_IS_SELECTED_2="TRANSFER_IS_SELECTED_2";

export const TANSFER_ADD_INCOME_DETAIL_SUCCESS="TANSFER_ADD_INCOME_DETAIL_SUCCESS";
export const TANSFER_ADD_INCOME_DETAIL_FAIL="TANSFER_ADD_INCOME_DETAIL_FAIL";
export const ACCOUNT_SELECTED_MONEY_ICON="ACCOUNT_SELECTED_MONEY_ICON";
export const EDIT_ACCOUNT_SELECTED_MONEY_ICON="EDIT_ACCOUNT_SELECTED_MONEY_ICON"
export const MONEY_TRANSFER_SELECTED_ITEM_1="MONEY_TRANSFER_SELECTED_ITEM_1";
export const MONEY_TRANSFER_SELECTED_ITEM_2="MONEY_TRANSFER_SELECTED_ITEM_2";
export const ACCOUNT_UPDATE_PROPS="ACCOUNT_UPDATE_PROPS"
export const ACCOUNT_RECEIVE_PROPS="ACCOUNT_RECEIVE_PROPS";
export const ADD_LOCAL_DATA="ADD_LOCAL_DATA"
export const UPDATE_TRANSFER_ITEM="UPDATE_TRANSFER_ITEM"
export const MONEY_TRANSFER_SCREEN_LOAD="MONEY_TRANSFER_SCREEN_LOAD"