export const UPDATE_PROPS = "UPDATE_PROPS"
export const DRAWER_ITEM_KEY = "DRAWER_ITEM_KEY"
export const DRAWER_COMPONENT_LOAD = "DRAWER_COMPONENT_LOAD"
export const CHANGE_INCOME_TEXT = "CHANGE_INCOME_TEXT";
export const FLATLIST_VISIBILITY = "FLATLIST_VISIBILITY";
export const INCOME_DETAIL_PAGE_LOAD = "INCOME_DETAIL_PAGE_LOAD";
export const HOME_REFRESH_ITEM = "HOME_REFRESH_ITEM";
export const NOTES_INPUT_CHANGE = "NOTES_INPUT_CHANGE";
export const IS_SELECTED = "IS_SELECTED";
export const CATEGORY_MODAL_VISIBLE = "CATEGORY_MODAL_VISIBLE";
export const CATEGORY_IS_SELECTED = "CATEGORY_IS_SELECTED";
export const DATE_CHANGED = "DATE_CHANGED";
export const FLATLIST_ITEM_SELECTED = "FLATLIST_ITEM_SELECTED";


export const ACCOUNT_FETCH_LIST_SUCCESS = "ACCOUNT_FETCH_LIST_SUCCESS";
export const ACCOUNT_FETCH_LIST_FAIL = "ACCOUNT_FETCH_LIST_FAIL";

export const HOME_ACCOUNT_FETCH_LIST_SUCCESS = "HOME_ACCOUNT_FETCH_LIST_SUCCESS";
export const HOME_ACCOUNT_FETCH_LIST_FAIL = "HOME_ACCOUNT_FETCH_LIST_FAIL";

export const ADD_INCOME_DETAIL_SUCCESS = "ADD_INCOME_DETAIL_SUCCESS";
export const ADD_INCOME_DETAIL_FAIL = "ADD_INCOME_DETAIL_FAIL";

export const GET_ACCOUNT_LIST_SUCCESS = "GET_ACCOUNT_LIST_SUCCESS";
export const GET_ACCOUNT_LIST_FAIL = "GET_ACCOUNT_LIST_FAIL";
export const HOME_UPDATE_PROPS = "HOME_UPDATE_PROPS"
export const HOME_RECIEVE_PROPS = "HOME_RECIEVE_PROPS"
export const VISIBLE_LIST = "VISIBLE_LIST";
export const ITEM_FLATLIST_SELECTED = "ITEM_FLATLIST_SELECTED"
export const TODAY_DATE = "TODAY_DATE";
export const YESTERDAY_DATE = "YESTERDAY_DATE";

export const INCOME_FETCH_LIST_SUCCESS = "INCOME_FETCH_LIST_SUCCESS";
export const INCOME_FETCH_LIST_FAIL = "INCOME_FETCH_LIST_FAIL";

export const FAVORITE_ITEM_ADDED_SUCCESS = "FAVORITE_ITEM_ADDED_SUCCESS";
export const FAVORITE_ITEM_ADDED_FAIL = "FAVORITE_ITEM_ADDED_FAIL";

export const UNFAVORITE_ITEM_SUCCESS = "UNFAVORITE_ITEM_SUCCESS";
export const UNFAVORITE_ITEM_FAIL = "UNFAVORITE_ITEM_FAIL";

export const DELETE_INCOME_DETAIL_SUCCESS = "DELETE_FAV_ITEM_SUCCESS";
export const DELETE_INCOME_DETAIL_FAIL = "DELETE_FAV_ITEM_FAIL";

export const STATISTICS_FLATLIST_VISIBLITY = "STATISTICS_FLATLIST_VISIBLITY";
export const STATISTICS_TODAY_DATE = "STATISTICS_TODAY_DATE";
export const STATISTICS_YESTERDAY_DATE = "STATISTICS_YESTERDAY_DATE";

export const INCOME_ACTIVE = "INCOME_ACTIVE";

export const EXPANCE_ACTIVE = "EXPANCE_ACTIVE";
export const EXPENCE_FLATLIST_VISIBILITY = "EXPENCE_FLATLIST_VISIBILITY";
export const EXPENCE_IS_SELECTED = "EXPENCE_IS_SELECTED";
export const EXPENCE_GET_ACCOUNT_LIST_SUCCESS = "EXPENCE_GET_ACCOUNT_LIST_SUCCESS";
export const EXPENCE_GET_ACCOUNT_LIST_FAIL = "EXPENCE_GET_ACCOUNT_LIST_FAIL";
export const EXPENCE_CATEGORY_MODAL_VISIBLE = "EXPENCE_CATEGORY_MODAL_VISIBLE";
export const EXPENCE_CATEGORY_IS_SELECTED = "EXPENCE_CATEGORY_IS_SELECTED";
export const EXPENCE_DATE_CHANGED = "EXPENCE_DATE_CHANGED";
export const EXPENCE_DETAIL_SELECTED_ACCOUNT_ITEMS = "EXPENCE_DETAIL_SELECTED_ACCOUNT_ITEMS"
export const EXPENCE_NOTES_INPUT_CHANGE = "EXPENCE_NOTES_INPUT_CHANGE";
export const EXPENCE_ADD_INCOME_DETAIL_FAIL = "EXPENCE_ADD_INCOME_DETAIL_FAIL";
export const EXPENCE_ADD_INCOME_DETAIL_SUCCESS = "EXPENCE_ADD_INCOME_DETAIL_SUCCESS";
export const EXPENCE_INCOME_DETAIL_FAIL = "EXPENCE_INCOME_DETAIL_FAIL";
export const EXPENCE_SELECTED_MONEY_ICON = "EXPENCE_SELECTED_MONEY_ICON"
export const EXPENCE_DETAIL_SCREEN_LOAD = "EXPENCE_DETAIL_SCREEN_LOAD"
export const EXPENCE_DETAIL_SELECTED_MONEY_ICON = "EXPENCE_DETAIL_SELECTED_MONEY_ICON";
export const EXPENCE_DETAIL_SELECTED_CATEGORY_ITEMS = "EXPENCE_DETAIL_SELECTED_CATEGORY_ITEMS"
export const EXPENCE_DETAIL_SET_ITEMS = "EXPENCE_DETAIL_SET_ITEMS"

export const GET_FAVOURITE_ITEM_SUCCESS = "GET_FAVOURITE_ITEM_SUCCESS";
export const GET_FAVOURITE_ITEM_FAIL = "GET_FAVOURITE_ITEM_FAIL";

export const GET_INFORMATION_SUCCESS = "GET_INFORMATION_SUCCESS";
export const GET_INFORMATION_FAIL = "GET_INFORMATION_FAIL";


export const SETTING_VISIBLE_LIST = "SETTING_VISIBLE_LIST";
export const MODAL_VISIBLE = "MODAL_VISIBLE";
export const UPDATE_INCOME_DETAIL_SUCCESS = "UPDATE_INCOME_DETAIL_SUCCESS";
export const UPDATE_EXPANCE_DETAIL_SUCCESS = "UPDATE_EXPANCE_DETAIL_SUCCESS";

export const SELECTED_MONEY_ICON = "SELECTED_MONEY_ICON";
export const HOME_SELECTED_MONEY_ICON = "HOME_SELECTED_MONEY_ICON";
export const INCOME_SELECTED_MONEY_ICON = "INCOME_SELECTED_MONEY_ICON";
export const SETTING_FLATLIST_ITEM_SELECT = "SETTING_FLATLIST_ITEM_SELECT";
export const SETTING_ITEM_SELECTED_ITEM = "SETTING_ITEM_SELECTED_ITEM";
export const SETTING_REVEIVE_PROPS = "SETTING_REVEIVE_PROPS"
export const SETTING_UPDATE_PROPS = "SETTING_UPDATE_PROPS"
export const INCOME_DETAIL_SELECTED_MONEY_ICON = "INCOME_DETAIL_SELECTED_MONEY_ICON";
export const INCOME_DETAIL_SCREEN_LOAD = "INCOME_DETAIL_SCREEN_LOAD"
export const INCOME_DETAIL_SELECTED_ACCOUNT_ITEMS = "INCOME_DETAIL_SELECTED_ACCOUNT_ITEMS"
export const INCOME_DETAIL_SELECTED_CATEGORY_ITEMS = "INCOME_DETAIL_SELECTED_CATEGORY_ITEMS"
export const INCOME_DETAIL_SET_ITEMS = "INCOME_DETAIL_SET_ITEMS"

export const STATISTICS_SELECTED_MONEY_ICON = "STATISTICS_SELECTED_MONEY_ICON";

export const ACCOUNT_DETAIL_SELECTED_MONEY_ICON = "ACCOUNT_DETAIL_SELECTED_MONEY_ICON";

export const ACCOUNT_DETAIL_FETCH_LIST_SUCCESS = "ACCOUNT_DETAIL_FETCH_LIST_SUCCESS";
export const ACCOUNT_DETAIL_FETCH_LIST_FAIL = "ACCOUNT_DETAIL_FETCH_LIST_FAIL";

export const ACCOUNT_DETAIL_VISIBLE_LIST = "ACCOUNT_DETAIL_VISIBLE_LIST";
export const ACCOUNT_DETAIL_TODAY_DATE = "ACCOUNT_DETAIL_TODAY_DATE";
export const ACCOUNT_DETAIL_YESTERDAY_DATE = "ACCOUNT_DETAIL_YESTERDAY_DATE";

export const ACCOUNT_DETAIL_INCOME_FETCH_LIST_SUCCESS = "ACCOUNT_DETAIL_INCOME_FETCH_LIST_SUCCESS";
export const ACCOUNT_DETAIL_INCOME_FETCH_LIST_FAIL = "ACCOUNT_DETAIL_INCOME_FETCH_LIST_FAIL";
export const DELETE_ACCOUNT_DETAIL_SUCCESS = "DELETE_ACCOUNT_DETAIL_SUCCESS";
export const DELETE_ACCOUNT_DETAIL_FAIL = "DELETE_ACCOUNT_DETAIL_FAIL";

export const ACCOUNT_DETIAL_ITEM_UNFAVOURITE_SUCCESS = "ACCOUNT_DETIAL_ITEM_UNFAVOURITE_SUCCESS";
export const ACCOUNT_DETIAL_ITEM_UNFAVOURITE_FAIL = "ACCOUNT_DETIAL_ITEM_UNFAVOURITE_FAIL";


export const STATISTIC_SCREEN_LOAD = "STATISTIC_SCREEN_LOAD"
export const STATISTICS_ACCOUNT_FETCH_LIST_SUCCESS = "STATISTICS_ACCOUNT_FETCH_LIST_SUCCESS";
export const STATISTICS_ACCOUNT_FETCH_LIST_FAIL = "STATISTICS_ACCOUNT_FETCH_LIST_FAIL";
export const STATISTICS_FLATLIST_ITEM = "STATISTICS_FLATLIST_ITEM";
export const STATISTICS_SELECTED_ITEM = "STATISTICS_SELECTED_ITEM";
export const STATISTICS_DATE_RANGE_PICKER = "STATISTICS_DATE_RANGE_PICKER";
export const STATISTICS_SELECTED_RANGE = "STATISTICS_SELECTED_RANGE";
export const STATISTICS_CHANGE_INDEX = "STATISTICS_CHANGE_INDEX";



export const DATE_RANGE_PICKER_DIALOG_VISIBLE = "DATE_RANGE_PICKER_DIALOG_VISIBLE";
export const SELECTED_RANGE = "SELECTED_RANGE"
export const ACCOUN_SCREEN_DATE_RANGE_PICKER_VISIBLE = "ACCOUN_SCREEN_DATE_RANGE_PICKER_VISIBLE";
export const SETTING_RESET = "SETTING_RESET";

export const ACCOUNT_FLATLIST_ITEM_SELECTED = "ACCOUNT_FLATLIST_ITEM_SELECTED"
export const ACCOUNT_SELECTED_RANGE = "ACCOUNT_SELECTED_RANGE"
export const ACCOUNT_ITEM_FLATLIST_SELECTED = "ACCOUNT_ITEM_FLATLIST_SELECTED"
export const SET_ACCOUNT_NAME = "SET_ACCOUNT_NAME"