export const ACCOUNT_INPUT_CHANGE="ACCOUNT_INPUT_CHANGE";
export const BALANCE_INPUT_CHANGE="BALANCE_INPUT_CHANGE";
export const BALANCE_INPUT_INVALID="BALANCE_INPUT_INVALID";
export const CREATE_NEW_ACCOUNT_SUCCESS ="CREATE_NEW_ACCOUNT_SUCCESS";
export const CREATE_NEW_ACCOUNT_FAIL ="CREATE_NEW_ACCOUNT_FAIL";
export const ADD_NEWACCOUNT_ITEM_SELECTED="ADD_NEWACCOUNT_ITEM_SELECTED";
export const ADD_NEWACCOUNT_COLOR_SELECTED="ADD_NEWACCOUNT_COLOR_SELECTED";
export const ADD_NEW_ACCOUNT_SCREEN_LOAD="ADD_NEW_ACCOUNT_SCREEN_LOAD"